### ISSUE TITLE
First Block found, but balance still zero

### ISSUE THREAD

**Issue by EternalWombat** [chiabluepool/bluepool#13]
So a hour ago the pool found it's first block but my balance in my account is still zero. I'm just under 1% of the pool size so there should be a reward

**Comment by mendogamers** [comment]
yes me too, i have 0 balance

**Comment by HailongZhu** [comment]
Did anyone got their rewards?

**Comment by EternalWombat** [comment]
Yeah just checked. I got it for both blocks. Just started the Withdraw process, but it is still in progress

Edit: Withdraw worked out, closing this now
