### ISSUE TITLE
Pool stats page displaying inaccurate numbers?

### ISSUE THREAD

**Issue by jmsuan** [chiabluepool/bluepool#18]
Probably doesn't belong on this git but idk where else to put it.

I've been checking the pool stats page to see if the pool has won any blocks yet, and it's been on two for a while now.
![image](https://user-images.githubusercontent.com/73461052/121989169-7a6d6700-cd50-11eb-91b8-0aeb3b099320.png)

Are these pool numbers accurate? Are all these plots valid and actively farming?
according to chiacalculator.com, that number of plots should be able to win around once every 3 hours, but bluepool still only has the first two listed, and people's balances are still zero of course.

If not 100% of the plots are valid, I don't know how difficult it would be to remove them from this number, but I just want an accurate reference when estimating this pool's performance.

Let me know if I'm missing something, thanks.

**Comment by EternalWombat** [comment]
Was just thinking the same. I expected at least 2 more blocks this morning.. 
The numbers also flucuate quiet a bit. 

In regards to the balance, I got rewards for both blocks and also was able to withdraw them.

**Comment by xiaolin1579** [comment]
![image](https://user-images.githubusercontent.com/10980342/122013856-ca980800-cde8-11eb-8f1a-35cb7e76d446.png)

**Comment by jmsuan** [comment]
Glad to know what I saw had some merit 😅
