### ISSUE TITLE
More Stats?

### ISSUE THREAD

**Issue by EternalWombat** [chiabluepool/bluepool#6]
Any Chance we can get some more Stats? 
For example active Users or Users currently plotting? Right now there are around 1700 Users and only 300 new plots being plotted. Even when we would assume that 300 Users are plotting 1 plot each (what probably isn't true, I'm currently making 5 at a time) the amount of active users would be realy low at around 17% of total users.

**Comment by chiabluepool** [comment]
Building that in dashboard is not priority in the next days, (preparing for official pooling protocol).  But I just peeked into the database and there are ~50 different users currently plotting
